### ISSUE TITLE
Missing Rakefile

### ISSUE THREAD

**Issue by vipyne** [Locrawfish/daily-take-home#1]
hi @Locrawfish, 
I cloned down the repo to run locally on my machine, but I think the `rakefile` is missing.  (Maybe there is another way around db migration? It's been a _minute_ since I've worked with rails 😂).  Is it possible to check in the `rakefile`? 
thanks!

**Comment by loren-m-crawford** [comment]
hey @vipyne! so sorry about that! will get that checked in :D
